export const storiesActions = {
  FETCH_TOP_STORIES_SUCCESS: 'FETCH_TOP_STORIES_SUCCESS',
  FETCH_TOP_STORIES_ERROR: 'FETCH_TOP_STORIES_ERROR',
  FETCH_TOP_STORIES: 'FETCH_TOP_STORIES',

  FETCH_NEW_STORIES_SUCCESS: 'FETCH_NEW_STORIES_SUCCESS',
  FETCH_NEW_STORIES_ERROR: 'FETCH_NEW_STORIES_ERROR',
  FETCH_NEW_STORIES: 'FETCH_NEW_STORIES',
};
export const detailsActions = {
  FETCH_DETAILS_SUCCESS: 'FETCH_DETAILS_SUCCESS',
  FETCH_DETAILS_ERROR: 'FETCH_DETAILS_ERROR',
  FETCH_DETAILS: 'FETCH_DETAILS',
  RESET: 'RESET',
};
export const pageSize = 20;
