export const storiesActions = {
  FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS',
  FETCH_STORIES_ERROR: 'FETCH_STORIES_ERROR',
  FETCH_STORIES: 'FETCH_STORIES',
  UPDATE_STORIES_PAGE: 'UPDATE_STORIES_PAGE',
};
export const detailsActions = {
  FETCH_DETAILS_SUCCESS: 'FETCH_DETAILS_SUCCESS',
  FETCH_DETAILS_ERROR: 'FETCH_DETAILS_ERROR',
  FETCH_DETAILS: 'FETCH_DETAILS',
  RESET: 'RESET',
};
export const pageSize = 8;
